Document: chklref
Title: Debian chklref Manual
Author: <insert document author here>
Abstract: This manual describes what chklref is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/chklref/chklref.sgml.gz

Format: postscript
Files: /usr/share/doc/chklref/chklref.ps.gz

Format: text
Files: /usr/share/doc/chklref/chklref.text.gz

Format: HTML
Index: /usr/share/doc/chklref/html/index.html
Files: /usr/share/doc/chklref/html/*.html
